subinclude("//build_defs:go")

package(go = {
    "go_version": "go1.22.0",
})

go_test(
    name = "go_version_test",
    srcs = ["go_version_test.go"],
    deps = [
        "//third_party/go:testify",
    ],
)
